# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/profile.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("proto/profile.proto", :syntax => :proto3) do
    add_message "rpc.ProfileRequest" do
      optional :app_secret, :string, 1
      optional :app_group_secret, :string, 2
      optional :app_name, :string, 3
      optional :access_token, :string, 4
      optional :cluster_name, :string, 5
    end
    add_message "rpc.Profile" do
      optional :id, :int32, 1
      optional :name, :string, 2
      optional :app_secret, :string, 3
      optional :app_group_name, :string, 4
      optional :max_tps, :int32, 5
      optional :cluster_name, :string, 6
      optional :consul_host, :string, 7
      optional :status, :string, 8
      optional :meta, :message, 9, "rpc.ProfileMeta"
    end
    add_message "rpc.ProfileMeta" do
      map :service_names, :string, :string, 1
      optional :kafka, :message, 2, "rpc.KafkaMeta"
      optional :elasticsearch, :message, 3, "rpc.ElasticsearchMeta"
    end
    add_message "rpc.KafkaMeta" do
      optional :topic_name, :string, 1
      optional :partition, :int32, 2
      optional :replication_factor, :int32, 3
      optional :consumer_group, :string, 4
    end
    add_message "rpc.ElasticsearchMeta" do
      optional :index_prefix, :string, 1
      optional :document_type, :string, 2
    end
    add_message "rpc.User" do
      optional :username, :string, 1
      optional :cluster_name, :string, 2
    end
    add_message "rpc.AuthResponse" do
      optional :status, :bool, 1
    end
  end
end

module Rpc
  ProfileRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.ProfileRequest").msgclass
  Profile = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.Profile").msgclass
  ProfileMeta = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.ProfileMeta").msgclass
  KafkaMeta = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.KafkaMeta").msgclass
  ElasticsearchMeta = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.ElasticsearchMeta").msgclass
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.User").msgclass
  AuthResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.AuthResponse").msgclass
end
